# This is a basic workflow to help you get started with Actions

name: Build and publish to nuget.org

# Controls when the workflow will run
on:
  release:
    types:
      - published

env:
  PACKAGE_OUTPUT_DIRECTORY: '${{ github.workspace }}/output'
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  MSBUILD_GITHUB_PROPERTIES: '/p:GITHUB_RUN_ID=${{ github.run_id }} /p:GITHUB_RUN_NUMBER=${{ github.run_number }} /p:GITHUB_REF_NAME=${{ github.ref_name }} /p:GITHUB_SHA=${{ github.sha }} /p:GITHUB_REPOSITORY=${{ github.repository }}'

jobs:
  build_publish_nuget:
    name: 'Build and publish nuget packages'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Install dotnet'
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: "./global.json"

      - name: 'Restore packages'
        run: dotnet restore ${{ env.MSBUILD_GITHUB_PROPERTIES }}

      - name: 'Build'
        run: dotnet build -c Release --no-restore ${{ env.MSBUILD_GITHUB_PROPERTIES }}

      - name: 'Pack'
        run: dotnet pack -c Release --no-build -o ${{ env.PACKAGE_OUTPUT_DIRECTORY }} ${{ env.MSBUILD_GITHUB_PROPERTIES }}

#      - name: 'Push packages'
#        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_ORG_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate
